package com.tong.test.interviewee;

public class Interviewee {
    private long intervieweeId;
    private String userName;
    private String password;
    private String firstName;
    private String lastName;
    private int dateCreated; // in format of MM/DD/YYYY -> MMDDYYYY
    //private File profilePic;


    public Interviewee() {
        /*
        intervieweeId = 999;
        userName = "default";
        password = "default";
        firstName = "default";
        lastName = "default";
        dateCreated = 11111111;
        */
    }

    public Interviewee(long intervieweeId,
                       String userName,
                       String password,
                       String firstName,
                       String lastName,
                       int dateCreated) {
        this.intervieweeId = intervieweeId;
        this.userName = userName;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateCreated = dateCreated;
    }

    public Interviewee(String userName,
                       String password,
                       String firstName,
                       String lastName,
                       int dateCreated) { //id is automatically generated by database.
        this.userName = userName;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateCreated = dateCreated;
    }

    public long getIntervieweeId() {
        return intervieweeId;
    }

    public String getUserName() {
        return userName;
    }

    public String getPassword() {
        return password;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public int getDateCreated() {
        return dateCreated;
    }

    public void setIntervieweeId(long intervieweeId) {
        this.intervieweeId = intervieweeId;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setDateCreated(int dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Override
    public String toString() {
        return "Interviewee{" +
                "intervieweeId=" + intervieweeId +
                ", userName='" + userName + '\'' +
                ", password='" + password + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", dateCreated=" + dateCreated +
                '}';
    }
}
